[2024-07-16T17:34:22.806+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T17:34:22.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_file.read_file_task manual__2024-07-16T17:34:20.360718+00:00 [queued]>
[2024-07-16T17:34:22.834+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_file.read_file_task manual__2024-07-16T17:34:20.360718+00:00 [queued]>
[2024-07-16T17:34:22.835+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T17:34:22.847+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_file_task> on 2024-07-16 17:34:20.360718+00:00
[2024-07-16T17:34:22.854+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6633) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T17:34:22.855+0000] {standard_task_runner.py:63} INFO - Started process 6635 to run task
[2024-07-16T17:34:22.856+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'read_file', 'read_file_task', 'manual__2024-07-16T17:34:20.360718+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmptfz3sioq']
[2024-07-16T17:34:22.858+0000] {standard_task_runner.py:91} INFO - Job 353: Subtask read_file_task
[2024-07-16T17:34:22.903+0000] {task_command.py:426} INFO - Running <TaskInstance: read_file.read_file_task manual__2024-07-16T17:34:20.360718+00:00 [running]> on host 4510c8d13d8e
[2024-07-16T17:34:22.993+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_file' AIRFLOW_CTX_TASK_ID='read_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T17:34:20.360718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T17:34:20.360718+00:00'
[2024-07-16T17:34:22.994+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T17:34:22.995+0000] {logging_mixin.py:188} INFO - data from data_text.txt
[2024-07-16T17:34:22.995+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T17:34:22.995+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 14, in read_file
    with open(filepath, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/produc.txt'
[2024-07-16T17:34:23.005+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=read_file, task_id=read_file_task, run_id=manual__2024-07-16T17:34:20.360718+00:00, execution_date=20240716T173420, start_date=20240716T173422, end_date=20240716T173423
[2024-07-16T17:34:23.017+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 353 for task read_file_task ([Errno 2] No such file or directory: '/opt/airflow/dags/data/produc.txt'; 6635)
[2024-07-16T17:34:23.029+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T17:34:23.056+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T17:34:23.057+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
