[2024-07-11T04:25:59.143+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: test_dag.print_hello_task manual__2024-07-11T03:59:05.641939+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
