[2024-07-16T06:21:58.959+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T06:21:58.984+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_file.read_file_task scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-07-16T06:21:58.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_file.read_file_task scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-07-16T06:21:58.993+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T06:21:59.008+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_file_task> on 2023-01-01 00:00:00+00:00
[2024-07-16T06:21:59.015+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2731) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T06:21:59.016+0000] {standard_task_runner.py:63} INFO - Started process 2733 to run task
[2024-07-16T06:21:59.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'read_file', 'read_file_task', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp2w1ry3n1']
[2024-07-16T06:21:59.019+0000] {standard_task_runner.py:91} INFO - Job 332: Subtask read_file_task
[2024-07-16T06:21:59.066+0000] {task_command.py:426} INFO - Running <TaskInstance: read_file.read_file_task scheduled__2023-01-01T00:00:00+00:00 [running]> on host 3d1f449535f3
[2024-07-16T06:21:59.168+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_file' AIRFLOW_CTX_TASK_ID='read_file_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2024-07-16T06:21:59.170+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T06:21:59.170+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T06:21:59.171+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 12, in read_file
    with open(filepath, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/hoang/airflow_noti/dags/data/data_test.txt'
[2024-07-16T06:21:59.183+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=read_file, task_id=read_file_task, run_id=scheduled__2023-01-01T00:00:00+00:00, execution_date=20230101T000000, start_date=20240716T062158, end_date=20240716T062159
[2024-07-16T06:21:59.196+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 332 for task read_file_task ([Errno 2] No such file or directory: '/home/hoang/airflow_noti/dags/data/data_test.txt'; 2733)
[2024-07-16T06:21:59.230+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T06:21:59.250+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T06:21:59.251+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
