[2024-07-11T14:10:07.173+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T14:10:07.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_kubernetes_job.run_kubernetes_job scheduled__2024-07-10T00:00:00+00:00 [queued]>
[2024-07-11T14:10:07.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_kubernetes_job.run_kubernetes_job scheduled__2024-07-10T00:00:00+00:00 [queued]>
[2024-07-11T14:10:07.209+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-11T14:10:07.233+0000] {taskinstance.py:2330} INFO - Executing <Task(KubernetesPodOperator): run_kubernetes_job> on 2024-07-10 00:00:00+00:00
[2024-07-11T14:10:07.240+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=335) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T14:10:07.241+0000] {standard_task_runner.py:63} INFO - Started process 337 to run task
[2024-07-11T14:10:07.242+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_kubernetes_job', 'run_kubernetes_job', 'scheduled__2024-07-10T00:00:00+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp3c9ypl7i']
[2024-07-11T14:10:07.245+0000] {standard_task_runner.py:91} INFO - Job 305: Subtask run_kubernetes_job
[2024-07-11T14:10:07.292+0000] {task_command.py:426} INFO - Running <TaskInstance: run_kubernetes_job.run_kubernetes_job scheduled__2024-07-10T00:00:00+00:00 [running]> on host 3d1f449535f3
[2024-07-11T14:10:07.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_kubernetes_job' AIRFLOW_CTX_TASK_ID='run_kubernetes_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-10T00:00:00+00:00'
[2024-07-11T14:10:07.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T14:10:07.405+0000] {pod.py:1121} INFO - Building pod task-write-data-mongo-o586afr6 with labels: {'dag_id': 'run_kubernetes_job', 'task_id': 'run_kubernetes_job', 'run_id': 'scheduled__2024-07-10T0000000000-a8fa36097', 'kubernetes_pod_operator': 'True', 'try_number': '2'}
[2024-07-11T14:10:07.419+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T14:10:07.420+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 591, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 599, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1130, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 283, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 291, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 233, in get_conn
    config.load_incluster_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.
[2024-07-11T14:10:07.434+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_kubernetes_job, task_id=run_kubernetes_job, run_id=scheduled__2024-07-10T00:00:00+00:00, execution_date=20240710T000000, start_date=20240711T141007, end_date=20240711T141007
[2024-07-11T14:10:07.453+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 305 for task run_kubernetes_job (Service host/port is not set.; 337)
[2024-07-11T14:10:07.496+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T14:10:07.539+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T14:10:07.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
