[2024-07-16T06:27:36.302+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T06:27:36.329+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_file.read_file_task manual__2024-07-16T06:27:33.988255+00:00 [queued]>
[2024-07-16T06:27:36.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_file.read_file_task manual__2024-07-16T06:27:33.988255+00:00 [queued]>
[2024-07-16T06:27:36.340+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T06:27:36.359+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_file_task> on 2024-07-16 06:27:33.988255+00:00
[2024-07-16T06:27:36.366+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2812) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T06:27:36.369+0000] {standard_task_runner.py:63} INFO - Started process 2814 to run task
[2024-07-16T06:27:36.370+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'read_file', 'read_file_task', 'manual__2024-07-16T06:27:33.988255+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp1t1anv8b']
[2024-07-16T06:27:36.372+0000] {standard_task_runner.py:91} INFO - Job 335: Subtask read_file_task
[2024-07-16T06:27:36.425+0000] {task_command.py:426} INFO - Running <TaskInstance: read_file.read_file_task manual__2024-07-16T06:27:33.988255+00:00 [running]> on host 3d1f449535f3
[2024-07-16T06:27:36.517+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_file' AIRFLOW_CTX_TASK_ID='read_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T06:27:33.988255+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T06:27:33.988255+00:00'
[2024-07-16T06:27:36.518+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T06:27:36.519+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T06:27:36.520+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 12, in read_file
    with open(filepath, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/hoang/project_kub/airflow-docker/data/data_test.txt'
[2024-07-16T06:27:36.529+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=read_file, task_id=read_file_task, run_id=manual__2024-07-16T06:27:33.988255+00:00, execution_date=20240716T062733, start_date=20240716T062736, end_date=20240716T062736
[2024-07-16T06:27:36.542+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 335 for task read_file_task ([Errno 2] No such file or directory: '/home/hoang/project_kub/airflow-docker/data/data_test.txt'; 2814)
[2024-07-16T06:27:36.583+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T06:27:36.595+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
